### ISSUE TITLE
about the checkpoints of nnU-Net

### ISSUE THREAD

**Issue by Alena-Xinran** [MrGiovanni/DiffTumor#13]
Hello Dear author:
When I used checkpoints of nnU-Net for validation, I encountered error as shown in the image. The error was not found in the other two backbones.
![微信截图_20240713102937](https://github.com/user-attachments/assets/13ef889b-ec61-4363-95d2-f516e2cbb520)

**Comment by qic999** [comment]
Hi @Aimee2004xin, thank you for your attention to our work! This error has been fixed. You can try the latest code.
