### ISSUE TITLE
Step2：LDM generation

### ISSUE THREAD

**Issue by TianmengHsu** [MrGiovanni/DiffTumor#17]
![image](https://github.com/user-attachments/assets/29388207-6785-47ab-8a9e-5421cd2ad2d0)
When I am generating images, it always looks like this. Do you have any idea why this is so? I have been trying to solve this problem for a long time.
It would be appreciated if you could provide the code for the inference phase!
Any help or guidance would be greatly appreciated!

**Comment by qic999** [comment]
@TianmengHsu You can reference this issue https://github.com/MrGiovanni/DiffTumor/issues/12
