### ISSUE TITLE
Parameter Count Mismatch

### ISSUE THREAD

**Issue by koukihk** [MrGiovanni/DiffTumor#4]
Hi, thank you for your excellent work!

I noticed there seem to be some minor issues in your code that could affect model validation.
Specifically, the problem appears to be on line 261 of the file DiffTumor/STEP3.SegmentationModel/validation.py, where there is a mismatch in parameter counts.

```
print(name, val_outputs[0].shape, \
	'dice: [{:.3f}  {:.3f}]; nsd: [{:.3f}  {:.3f}]'.format(current_liver_dice, current_tumor_dice, current_liver_nsd, current_tumor_nsd), \
	'time {:.2f}s'.format(time.time() - start_time))
```

Additionally, I believe renaming some variables would be beneficial, such as changing 'liver_dice' to 'organ dice'.😊

```
liver_dice = []
liver_nsd  = []
```

**Comment by TaylorRex** [comment]
感谢您出色的工作！
我在验证的过程中也出现了相同的参数计数不匹配的问题，问题发生在DiffTumor/STEP3.SegmentationModel/validation.py 的第 261 行
![image](https://github.com/MrGiovanni/DiffTumor/assets/100455315/f233e440-c118-490d-9bb8-0b1cf5c34877)

**Comment by qic999** [comment]
@koukihk @TaylorRex Thank you for your attention to our work and for finding these mistakes. We have updated the code in DiffTumor/STEP3.SegmentationModel/validation.py accordingly.
