### ISSUE TITLE
about training

### ISSUE THREAD

**Issue by Devil-Ideal** [MrGiovanni/DiffTumor#7]
Thank you for your work. There are some details I'm not sure. What type of GPU did you use when training the model? How much video memory is required? How many GPUs are needed for training? What is the approximate training time?

**Comment by qic999** [comment]
@Devil-Ideal Thank you for your attention to our work. We used one A100 80G GPU to train Stage 1 for approximately 4 days and one V100 16G GPU to train Stage 2 and Stage 3 for approximately 1 day.

**Comment by Devil-Ideal** [comment]
> @Devil-Ideal Thank you for your attention to our work. We used one A100 80G GPU to train Stage 1 for approximately 4 days and one V100 16G GPU to train Stage 2 and Stage 3 for approximately 1 day.

How many epochs are trained during stage 3? I don't use the cachedataset, and the max epoch is set to 1000, the training process nearly takes  10 days (QAQ)

**Comment by qic999** [comment]
> > @Devil-Ideal Thank you for your attention to our work. We used one A100 80G GPU to train Stage 1 for approximately 4 days and one V100 16G GPU to train Stage 2 and Stage 3 for approximately 1 day.
> 
> How many epochs are trained during stage 3? I don't use the cachedataset, and the max epoch is set to 1000 with batchsize=2, the training process nearly takes 10 days (QAQ)

If you don't have enough CPU memory, you can try using the PersistentDataset class in MONAI.

**Comment by Devil-Ideal** [comment]
> > > @Devil-Ideal Thank you for your attention to our work. We used one A100 80G GPU to train Stage 1 for approximately 4 days and one V100 16G GPU to train Stage 2 and Stage 3 for approximately 1 day.
> > 
> > 
> > How many epochs are trained during stage 3? I don't use the cachedataset, and the max epoch is set to 1000 with batchsize=2, the training process nearly takes 10 days (QAQ)
> 
> If you don't have enough CPU memory, you can try using the PersistentDataset class in MONAI.

Thanks again for your reply !
