### ISSUE TITLE
about dataset

### ISSUE THREAD

**Issue by koukihk** [MrGiovanni/DiffTumor#8]
Hey there, thanks a bunch for the awesome work! 
I noticed you provided a download link for Task03_Liver.tar.gz in the README, which contains imagesTr and labelsTr. This looks pretty similar to the 04_LiTS.tar.gz you shared earlier – it seems like they're different releases for the Liver Tumor Segmentation Challenge (LiTS), but they perform differently when used for model training. Could you please let me know what the difference is between the two? I'd really appreciate it!

**Comment by qic999** [comment]
@koukihk Task03_liver is the MSD liver dataset, which is, in fact, the same dataset as LiTS. I did not quite understand what you meant by 'they perform differently when used for model training'.
